# Имя workflow (видно на вкладке Actions)
name: CI - pytest

# Когда запускать: на любой push и на pull request
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
        # requirements-test.txt содержит pytest и torch (CPU-колёса)

      - name: Install package (editable)
        run: pip install -e .
        # editable-установка обеспечивает корректные импорты tiny_transformer

      - name: Run tests
        run: pytest -q
